### PR TITLE
Primitive browser support

### PR DESCRIPTION
**Pull request by colagrosso**
See discussion in issue #126

### CODE REVIEW

**Comment by acabal** [comment]
This looks great! The only comment I would make is that the `EreaderBrowser` class isn't really necessary, as it's only used in one place and is not a logical "object" per se. Instead we can just put that `if` logic straight into the header template. If later on we find that we need to make that same check somewhere else, we can create a class or reusable function then.

**Comment by colagrosso** [comment]
Thanks for the quick review. We need the check in `Header.php` and `SearchForm.php`. I'm open to a different way to make a reusable function because you're right that it's not a logical object.

**Comment by colagrosso** [comment]
Good call, done.

**Comment by acabal** [comment]
Excellent, thanks!

**Pull request merged**
