### PR TITLE
Add authors page

### PR DESCRIPTION
**Pull request by donatj**
Finishes #189 

Here's the basic authors page I was talking about.

image

I don't have the full set populated so my screenshot is limited.

I'm more than happy to change anything. I tried my best to match the pre-existing coding style.

### CODE REVIEW

**Comment by acabal** [comment]
This is great, thanks! Some notes:

- We should sort authors by their sort name, not their regular name. Also note that `<=>` is not Unicode aware so it will sort names like `Karel Čapek` incorrectly. You should sort using a collator, see https://github.com/standardebooks/web/blob/f9665ee339a93d0774012df51aac757e536b60f3/lib/Library.php#L368 for a pattern to follow.
- When running on my machine, PHP gives an error that `$authors->AuthorsUrl` is undefined. Instead you should do `<?= '/ebooks/' . $author->UrlName ?>`.
- Some ebooks can have more than one author, like https://standardebooks.org/ebooks/karl-marx_friedrich-engels/the-communist-manifesto/samuel-moore so you should use `strip_tags($ebook->AuthorsHtml)` to get the author "name" instead. However you can *sort* that name by using `$ebook->Authors[0]->SortName`.

Some testing books for you to add are:

-https://standardebooks.org/ebooks/karel-capek/r-u-r/paul-selver_nigel-playfair
-https://standardebooks.org/ebooks/karl-marx_friedrich-engels/the-communist-manifesto/samuel-moore
-https://standardebooks.org/ebooks/samuel-butler-1612-1680/hudibras (note the strange author slug, to differentiate between another author named `Samuel Butler`.

**Comment by donatj** [comment]
@acabal - [Here's my proposed solution](https://github.com/standardebooks/web/pull/191/commits/1157d02fa0842ec2febc70b6b5d820a4b6882e21) - I'm happy to revert it if it doesn't work for you.

Essentially we create pages for the _individual authors_ in addition to the group pages. 

This way, if we have someone who wrote a book individually and as a group their individual author page would list both.

**Comment by donatj** [comment]
Just incase it wasn't obvious, you have to rebuild your book cache to test my code here.

**Comment by acabal** [comment]
I don't think we're ready yet to split multi-author works like Communist Manifesto into their individual authors quite yet. This is because bulk downloads/feeds are grouped by author group and not individual authors, and the author links themselves in an ebook page (i.e. clicking on the author name below the book title in the ebook detail view) leads to the group author page too. Group authors are treated like one unit across the entire site. 

If think it's a good proposal to split them up, but if we do that then we should do it across the site as a whole for consistency. I think that's out of scope for this PR right now.

Also, you've added `$collator` but you didn't define or instantiate it. How can this run on your machine without crashing?

**Comment by acabal** [comment]
Closed due to inactivity. If you have time to wrap this up feel free to reopen the PR. Thanks!

**Pull request closed without merging**
