### PR TITLE
Add how-to poem guide

### PR DESCRIPTION
**Pull request by EmmaSweeney**

### CODE REVIEW

**Comment by acabal** [comment]
Great work Emma. I think this would benefit from a few screenshots so people can see what the styling actually looks like. Can you put that together? You can put them in the `www/images` folder, make sure to use both avif and jpg plus @2x variants (see other images in that folder for an example of what I mean).

**Comment by EmmaSweeney** [comment]
I knew I was forgetting something. I'll have this done in the next couple of days.

**Comment by EmmaSweeney** [comment]
Ok, this has pictures now.

**Comment by acabal** [comment]
Great work, thanks!

**Pull request merged**
