### PR TITLE
Add guide to common issues in converting from PD transcriptions

### PR DESCRIPTION
**Pull request by vr8hub**
All right, here is the first pass. I did this originally as an .rst file based on the manual, which made the classes all wrong for something like the step-by-step. So I mostly did this by hand, using the Step-by-Step as a template of sorts. I'm sure there are mistakes; let me know what needs to be fixed and/or reworded.

### CODE REVIEW

**Comment by acabal** [comment]
Thanks Vince. There's a lot of broken XHTML in here, which is causing failed rendering. If you can't get the website to work locally, then I suggest saving the non-PHP bits of this file into an XHTML file, then adding the headers and footers from the actual SE website which you can get by using view source. Then, open that XHTML file in your browser and it'll tell you where all the parse errors are.

**Comment by vr8hub** [comment]
OK, will do.

**Comment by vr8hub** [comment]
It was mostly just missing closing code tags. However, the last item, which is a blockquote, is not displaying correctly, even with all the CSS links in the header (copied from the Step-by-Step page). I have it formatted like the formatted HTML in the Step-by-Step, e.g. using tags at the beginning of the lines for indenting. If I need to do something different, let me know.

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
