### PR TITLE
Populate the wanted list from placeholders in the DB

### PR DESCRIPTION
**Pull request by colagrosso**
This depends on having a DB populated with set of wanted-list placeholders you're happy with, so save a copy of the old wanted list and be prepared to revise some `Notes`, `TranscriptionUrl`s, etc. In my quick check there were several discrepancies.

Here's what the beginner list currently looks like in production:

image

and here it is with the same data from the DB (Note the difference on how collections are displayed):

image

Here is a snippet that shows what `Notes` and translators look like:

image

I added extra data for admins, but it could use a better design:

image

I figured admins would want a link to the placeholder. Maybe all users would want that link, too? I decided no for right now because the wanted list has almost all the info that regular users can see on the placeholder anyway.

### CODE REVIEW

**Comment by colagrosso** [comment]
Two other comments:

* I planned to use `Db::MultiTableSelect()` to select both the `Ebook` and `EbookPlaceholder` records in one query, but I decided not to. The wanted list needs the `Ebook`, `EbookPlaceholder`, and all the `Contributor` objects. There are many `Contributor`s to an `Ebook`, so that won't work with the joins needed for `Db::MultiTableSelect()`.  Performance seems fine to select all the `Ebook`s, then do individual lookups for the `EbookPlaceholder`s and `Contributor`s.
* `Ebook`s with a `NULL` for `EbookPlaceholder->Difficulty` are not shown.

**Comment by acabal** [comment]
Looks great! Some small notes:

- The wanted list shouldn't be a template - it will never be re-used outside of that one file. Just inline that stuff into the file.
- Let's rename the `CollectionFormatted` template, that's not descriptive of what it is. Formatted how? Maybe something like `CollectionDescriptor` instead.
- Instead of a new `MarkdownToInlineHtml` function, let's add an argument to the original `MarkdownToHtml` function: `MarkdownToHtml(?string $text, bool $singleLine = false)`
- Rename `GetWantedByDifficulty` for consistency to `GetByIsWantedAndDifficulty`

Hendrik has updated his spreadsheet with more collection info and all of the books on the wanted list. Can you ingest that spreadsheet into your script again to create the insert SQL? Then I can test it on the live data before continuing.

Thanks!

**Comment by colagrosso** [comment]
Thanks for the notes and the explanations behind them. I made 4 small commits to address the notes if it's easier to review that way. You can squash and merge when we'r'e done.

You should take an extra look at how I removed and inlined the wanted list template: https://github.com/standardebooks/web/pull/449/commits/57fa28f49fd57da2c2f909bd4ba2c316e0ef95e3

> Hendrik has updated his spreadsheet with more collection info and all of the books on the wanted list. Can you ingest that spreadsheet into your script again to create the insert SQL? Then I can test it on the live data before continuing.

Hmm, I see edits to the spreadsheet up to Dec 23, but the spreadsheet doesn't have the books on the wanted list anymore. I think your [advice](https://groups.google.com/g/standardebooks/c/NkifJymeA9I/m/CRWxrW3fAQAJ) from Dec 13 was to remove the entries that were already ingested. I can re-add them from a previous revision, and I'll put them in a different sheet. It will just take a bit of time.

**Comment by acabal** [comment]
Great thanks!

Re. spreadsheet, sorry, I was mistaken. The wanted list is already in the DB. However I believe the current spreadsheet (all 3 sheets) is all new items so we have to re-ingest it anyway. Can you run it through your script to create the SQL

**Comment by colagrosso** [comment]
Congrats on launching the new version of the wanted list\! The new design looks clean.

I either misunderstood your note about the template for wanted ebooks, or I wasn't clear in the original PR that the template was reused for beginner, intermediate, and advanced sections. Your template in c43c4fa2dd35a5c9011d0c1d9913df41c653c819 look good.

I compared the [old](https://web.archive.org/web/20241225220651/https://standardebooks.org/contribute/wanted-ebooks) list to what's in production, and saw some notes and other data that got lost. Here's what I suggest adding back:

### **Add Markdown notes**

(*Some of the "omnibus" notes might be obvious and removed on purpose, I don't know. You can skip them.*)

* [https://standardebooks.org/ebooks/heinrich-kramer/malleus-malleficarum/montague-summers](https://standardebooks.org/ebooks/heinrich-kramer/malleus-malleficarum/montague-summers)  
`[Page scans](https://catalog.hathitrust.org/Record/000584799).`

* [https://standardebooks.org/ebooks/ernest-thompson-seton/wild-animals-i-have-known](https://standardebooks.org/ebooks/ernest-thompson-seton/wild-animals-i-have-known)  
PG transcription has removed formatting.

* [https://standardebooks.org/ebooks/robert-southey/the-curse-of-kehama](https://standardebooks.org/ebooks/robert-southey/the-curse-of-kehama)  
`[Vol. 2](https://www.gutenberg.org/ebooks/55459).`

* [https://standardebooks.org/ebooks/j-w-von-goethe/william-meisters-apprenticeship/thomas-carlyle](https://standardebooks.org/ebooks/j-w-von-goethe/william-meisters-apprenticeship/thomas-carlyle)  
`[Page scans](https://books.google.com/books?id=HIxaAAAAYAAJ).`

* [https://standardebooks.org/ebooks/peter-christen-asbjornsen\_jorgen-moe/norwegian-folktales/george-dasent](https://standardebooks.org/ebooks/peter-christen-asbjornsen_jorgen-moe/norwegian-folktales/george-dasent)  
`[Part 2](https://gutenberg.org/ebooks/36385).`

* (Links to Winter, Summer, and Spring got lost in the notes) [https://standardebooks.org/ebooks/wladyslaw-reymont/the-peasants/michael-h-dziewicki](https://standardebooks.org/ebooks/wladyslaw-reymont/the-peasants/michael-h-dziewicki)  
`Transcription required; see [Winter](https://archive.org/details/thepeasants-winter), [Summer](https://archive.org/details/thepeasants-summer), [Spring](https://archive.org/details/thepeasants-spring).`

* [https://standardebooks.org/ebooks/vernon-lee/short-fiction](https://standardebooks.org/ebooks/vernon-lee/short-fiction)  
Add Transcription URL: [https://www.gutenberg.org/ebooks/author/2683](https://www.gutenberg.org/ebooks/author/2683)  
To be compiled in an omnibus “Short Fiction.”

* [https://standardebooks.org/ebooks/sheridan-le-fanu/short-fiction](https://standardebooks.org/ebooks/sheridan-le-fanu/short-fiction)  
To be compiled in an omnibus “Short Fiction.”

* [https://standardebooks.org/ebooks/william-mcgonagall/poetry](https://standardebooks.org/ebooks/william-mcgonagall/poetry)  
To be compiled in an omnibus.

* [https://standardebooks.org/ebooks/manly-wade-wellman/short-fiction](https://standardebooks.org/ebooks/manly-wade-wellman/short-fiction)  
To be compiled into a “Short Fiction” omnibus.

* [https://standardebooks.org/ebooks/algernon-blackwood/short-fiction](https://standardebooks.org/ebooks/algernon-blackwood/short-fiction)  
To be compiled in an omnibus “Short Fiction.”

* [https://standardebooks.org/ebooks/jack-london/short-fiction](https://standardebooks.org/ebooks/jack-london/short-fiction)  
`To be compiled in a “Short Fiction” omnibus. We already have three short story compilations that must be rolled into this one. [See this bibliography spreadsheet](https://docs.google.com/spreadsheets/d/1yXZvlZVekVY3EpearMW8QIrbBEJlm8RbEXAuZP5rTG4/edit?usp=sharing).`

### **Add Transcription URLs**

[https://standardebooks.org/ebooks/mark-akenside/poetry](https://standardebooks.org/ebooks/mark-akenside/poetry)  
Transcription URL: [https://www.gutenberg.org/ebooks/9814](https://www.gutenberg.org/ebooks/9814)

[https://standardebooks.org/ebooks/henry-williamson/tarka-the-otter](https://standardebooks.org/ebooks/henry-williamson/tarka-the-otter)  
Transcription URL: [https://archive.org/stream/in.ernet.dli.2015.210843/2015.210843.Tarka-The\_djvu.txt](https://archive.org/stream/in.ernet.dli.2015.210843/2015.210843.Tarka-The_djvu.txt)   
But the notes also read that transcription is required, so I don't know.

### **Add page scans as notes**

These books had links to page scans that got lost because they were on the title where the transcription URL should be. They seem useful, so consider adding them as notes.

[https://standardebooks.org/ebooks/edmond-rostand/cyrano-de-bergerac/brian-hooker](https://standardebooks.org/ebooks/edmond-rostand/cyrano-de-bergerac/brian-hooker)  
`[Page scans](https://books.google.com/books?id=OKREAAAAYAAJ).`

[https://standardebooks.org/ebooks/catalina-de-erauso/the-nun-ensign/james-fitzmaurice-kelly](https://standardebooks.org/ebooks/catalina-de-erauso/the-nun-ensign/james-fitzmaurice-kelly)  
`[Page scans](https://archive.org/details/nunensign00erauuoft).`

[https://standardebooks.org/ebooks/st-john-of-the-cross/poetry](https://standardebooks.org/ebooks/st-john-of-the-cross/poetry)  
`[Page scans](https://archive.org/details/completeworksofs02johnuoft/page/n17/mode/2up).`

[https://standardebooks.org/ebooks/cyril-kay-scott/sinbad-a-romance](https://standardebooks.org/ebooks/cyril-kay-scott/sinbad-a-romance)  
`[Page scans](https://archive.org/details/sinbadromance00scot).`

[https://standardebooks.org/ebooks/cyril-kay-scott/blind-mice](https://standardebooks.org/ebooks/cyril-kay-scott/blind-mice)  
`[Page scans](https://archive.org/details/blindmice00compgoog/page/n6/mode/2up).`

[https://standardebooks.org/ebooks/norbert-jacques/dr-mabuse-the-gambler/lilian-a-clare](https://standardebooks.org/ebooks/norbert-jacques/dr-mabuse-the-gambler/lilian-a-clare)  
`[Page scans](https://archive.org/details/mabuse-norbert-jacques-1921-eng/page/8/mode/1up).`

**Comment by colagrosso** [comment]
Regarding the spreadsheet: Here is a new [se-placeholders.sql](https://gist.githubusercontent.com/colagrosso/7fc986a0844157af7cd048f5f0018541/raw/59b779ab728645c4e5f0163488c0fd0fae8df083/se-placeholders.sql) that you can use to ingest the new placeholders.

I processed only the first sheet, titled "List" because that's all that's needed. The sheet titled "Página5" are duplicate rows of what's on "List," and all the rows in "Copyrighted works" are already in the DB.

I made some updates to the "List" sheet, FYI only.

* Added sequence numbers to the Harper Novel Prize Winners  
* Removed the row for [*The Perennial Bachelor*](https://standardebooks.org/ebooks/anne-parrish/the-perennial-bachelor) because it's already in the DB and on the wanted list with the correct data  
* Removed the row for [*Lost Illusions*](https://standardebooks.org/ebooks/honore-de-balzac/lost-illusions/ellen-marriage) because it's already in the DB and on the wanted list with the correct data  
* Removed the row for [*The Murder of Roger Ackroyd*](https://standardebooks.org/ebooks/agatha-christie/the-murder-of-roger-ackroyd) because it's already released with the correct data  
* Renamed "The Human Comedy" series to be consistent  
* Removed all instances of "??" for translators and year published and left them blank  
* Corrected *Paroles* publication date to 1946  
* Removed these publication years because I didn't know which one to keep and there can be only one. There seem to be multiple sub-works that were published in different years.  
  * *The Celibates*, 1832—1842  
  * *Parisians in the Country*, 1833—1843  
  * *Jealousies of a Country Town*, 1836—1839  
  * *Lost Illusions*, 1837—1843  
* Set `ebook-placeholder-is-wanted` to FALSE for all entries that were blank. Now all rows are FALSE, so the transcription URLs and notes will be ignored.  
* Removed duplicate row for *The Dead Letter* by Regester Seeley

I also had to remove these 7 rows from the "List" sheet because they are already in the DB, but the DB needs updating:

* Removed the row for [*Tarka the Otter*](https://standardebooks.org/ebooks/henry-williamson/tarka-the-otter), but that placeholder needs this update:  
  * Number 9 in Hawthornden Prize Winners  
* Removed the row for [*Memoirs of a Fox-Hunting Man*](https://standardebooks.org/ebooks/siegfried-sassoon/memoirs-of-a-fox-hunting-man), but that placeholder needs this update:  
  * Number 10 in Hawthornden Prize Winners  
* Removed the row for [*Without My Cloak*](https://standardebooks.org/ebooks/kate-obrien/without-my-cloak), but that placeholder needs this update:  
  * Number 13 in Hawthornden Prize Winners  
* Removed the row for [*I, Claudius*](https://standardebooks.org/ebooks/robert-graves/i-claudius), but that placeholder needs this update:  
  * Number 17 in Hawthornden Prize Winners  
* Removed the row for [*The Maltese Falcon*](https://standardebooks.org/ebooks/dashiell-hammett/the-maltese-falcon), but that placeholder needs this update:  
  * Haycraft-Queen Cornerstones  
* Removed the row for [*The Informer*](https://standardebooks.org/ebooks/liam-oflaherty/the-informer), but that placeholder needs this update:  
  * Haycraft-Queen Cornerstones  
* Removed the row for [*The Nine Tailors*](https://standardebooks.org/ebooks/dorothy-l-sayers/the-nine-tailors), but that placeholder needs this update:  
  * Haycraft-Queen Cornerstones

I put together [se-placeholders-2.sql](https://gist.githubusercontent.com/colagrosso/7fc986a0844157af7cd048f5f0018541/raw/973a751101a43b17ecdf643093affd2bafc7a91e/se-placeholders-2.sql) that you can use to update those placeholders on the production site.

**Comment by acabal** [comment]
> I either misunderstood your note about the template for wanted ebooks, or I wasn't clear in the original PR that the template was reused for beginner, intermediate, and advanced sections. Your template in https://github.com/standardebooks/web/commit/c43c4fa2dd35a5c9011d0c1d9913df41c653c819 look good.

Yes, this was my mistake. I was looking too quickly and didn't realize it was re-used three times in that page. So your initial structure was correct after all. This has been a rough month - various illnesses and a lot of holidays - sorry for the many mixups!

Thanks for taking care of the spreadsheet, and the corrections! I've applied the corrections and will apply the spreadsheet shortly.

As I'm editing these placholders I notice it's taking 2+ seconds to POST from the placeholder edit form. That's a pretty long time. It's not a critical issue but if you have spare time it might be worth profiling that code path to see what's taking so long. As far as I can tell all of the queries involved use indexes but I don't have time to look at it deeper right now.

**Comment by colagrosso** [comment]
> As I'm editing these placeholders I notice it's taking 2+ seconds to POST from the placeholder edit form. That's a pretty long time. It's not a critical issue but if you have spare time it might be worth profiling that code path to see what's taking so long. As far as I can tell all of the queries involved use indexes but I don't have time to look at it deeper right now.

Weird. I'll check it out.

**Pull request merged**
