### PR TITLE
Script to update/insert existing cover art in the database

### PR DESCRIPTION
**Pull request by colagrosso**
Hi @jobcurtis,

Here's a script I've been refining for a while, and I'm happy with it and eager for your feedback. I tested it by syncing and building all published ebooks locally and using the `deploy-ebook-to-www` script. The script can now update the database at the same time, but if you already have deployed all the ebooks, you can do a second loop over them like this:

```bash
cd /standardebooks.org/ebooks
for BOOK in $(find . -maxdepth 1 -type d); do
  /standardebooks.org/web/scripts/deploy-ebook-to-www -v --no-images --no-build  --no-epubcheck --no-recompose --no-feeds --no-bulk-downloads --upsert-to-cover-art-database $BOOK
done
```

It handles the common cases: 

1. Inserting a new image into the DB
2. Updating the status of an existing approved/unverified image to `in_use` by the correct ebook
3. No-op if the image is already in the DB and marked as `in_use`

One edge case it doesn't handle is that 29 repos out of the 878 that I ran it don't have a `images/cover.source.jpg`. They have a `images/cover.source.png` instead ([example](https://github.com/standardebooks/a-merritt_the-moon-pool/blob/master/images/cover.source.png)):

```
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/a-merritt_the-moon-pool.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/adam-smith_the-wealth-of-nations.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/agatha-christie_the-secret-adversary.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/alain-rene-lesage_gil-blas_tobias-smollett.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/black-hawk_the-autobiography-of-ma-ka-tai-me-she-kia-kiak-or-black-hawk.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/e-pauline-johnson_legends-of-vancouver.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/edith-wharton_ethan-frome.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/f-scott-fitzgerald_the-great-gatsby.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/h-rider-haggard_cleopatra.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/harold-frederic_the-damnation-of-theron-ware.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/henry-adams_democracy.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/henry-david-thoreau_a-week-on-the-concord-and-merrimack-rivers.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/hugh-walpole_the-dark-forest.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/j-s-fletcher_the-middle-temple-murder.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/j-w-von-goethe_the-sorrows-of-young-werther_r-d-boylan.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/john-w-campbell_invaders-from-the-infinite.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/john-w-campbell_islands-of-space.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/john-w-campbell_the-black-star-passes.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/lewis-carroll_through-the-looking-glass_john-tenniel.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/lord-dunsany_the-gods-of-pegana.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/oliver-goldsmith_the-vicar-of-wakefield.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/p-t-barnum_the-art-of-money-getting.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/peter-kropotkin_mutual-aid.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/thomas-carlyle_sartor-resartus.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/thornton-w-burgess_green-forest-stories.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/washington-irving_the-sketch-book-of-geoffrey-crayon-gent.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/william-makepeace-thackeray_vanity-fair.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/william-shakespeare_pericles.git
Error: no images/cover.source.jpg in /standardebooks.org/ebooks/william-shakespeare_richard-iii.git
```

The script doesn't look for the PNG, and our PHP code expects a JPEG anyway, so I think it's OK. I'm not sure that 100% coverage of the existing ebooks is high priority right now.

### CODE REVIEW

**Comment by colagrosso** [comment]
One other edge case/known issue I forgot to mention: Some artwork titles have `<span>`s in them that my parsing doesn't pick up. For example, the title of this painting used in _Twelfth Night_:

https://github.com/standardebooks/william-shakespeare_twelfth-night/blob/9b09e07ec836b5a209ec50c534756c45a6cc1be4/src/epub/text/colophon.xhtml#L30

```html
<i epub:type="se:name.visual-art.painting">Olivia, Maria and Malvolio from “Twelfth Night,” Act <span epub:type="z3998:roman">III</span>, Scene <span epub:type="z3998:roman">IV</span></i>
```

Should be:

```
Olivia, Maria and Malvolio from “Twelfth Night,” Act III, Scene IV
```

but as you can see here:

https://143.198.245.16/artworks/johann-heinrich-ramberg/olivia-maria-and-malvolio-from-twelfth-night-act-scene

it got parsed as:

```
Olivia, Maria and Malvolio from “Twelfth Night,” Act , Scene
```

I'm pretty sure my XML handling in `scripts/upsert-to-cover-art-database` is the culprit:

```php
$artworkName = NullIfEmpty($colophonXml->xpath('/html/body/main/section/p/i[@epub:type="se:name.visual-art.painting"]'));
```

but I'm inclined to leave it for now unless I'm missing an easy way to make it include children elements.

**Comment by colagrosso** [comment]
Ok, there are 37 artwork titles that have inner tags like `<abbr>` and `<span>` like the example above:

```html
<i epub:type="se:name.visual-art.painting">Olivia, Maria and Malvolio from “Twelfth Night,” Act <span epub:type="z3998:roman">III</span>, Scene <span epub:type="z3998:roman">IV</span></i>
```

```
+------------------------------------+----------------------------------------------------------------------------------------+                              
| Name                               | substring(art.Name, 1, 80)                                                             |                              
+------------------------------------+----------------------------------------------------------------------------------------+                              
| Alexandre Jacovleff                | The General Mas Sou in the History Piece The Retreat of Kiai-Ting                      |      
| Anonymous                          | King Henry VI                                                                          |
| Arthur Hacker                      | Henry Payne, Esq. J.P.                                                                 |
| Childe Hassam                      | St. Patrick’s Day                                                                      |
| Cyrus Cuneo                        | Mr. Smith                                                                              |
| Douglas Strachan                   | James Cromar Watt, L.L.D.                                                              |
| Edmund Dulac                       | Quatrain XI                                                                            |
| Ernst Josephson                    | The Danish author J. P. Jacobsen                                                       |
| Ethel Franklin Betts               | “I Am Not⁠—I Am Not Dreaming!”                                                          |
| Francis Wheatley                   | A Scene From Shakespeare’s The Tempest                                                 |
| George Catlin                      | Meach-o-shín-gaw, Little White Bear, a Distinguished Brave                             |
| Henry Ward Ranger                  | Bradbury’s Mill Pond, No. 2                                                            |
| Howard Cushing                     | Mrs. Ethel Cushing                                                                     |
| Ilya Repin                         | Portait of T. G. Shevchenko                                                            |
| James Abbott McNeill Whistler      | Symphony in White, No. 1: The White Girl                                               |
| Jean-Baptiste Messier              | Esquisse pour l’ancien Hôtel de Ville de Paris: Brissac négociant auprès des éch       |
| Johann Heinrich Ramberg            | Olivia, Maria and Malvolio from “Twelfth Night,” Act III, Scene IV                     |
| John Collier                       | Pope Urban VI                                                                          |
| John Covert                        | The Temptation of St. Anthony                                                          |
| John Gilbert                       | Richard II Resigning the Crown to Bolingbroke                                          |
| John Singer Sargent                | Mrs. George Swinton (Elizabeth Ebsworth)                                               |
| John Singer Sargent                | Elizabeth Winthrop Chanler (Mrs. John Jay Chapman)                                     |
| Joseph-Marie Vien                  | Portrait de Louis XVII, à la prison du temple                                          |
| Józef Brandt                       | Departure of John III Sobieski and Marysieńka Sobieska from Wilanów                    |
| Lawren Harris                      | Snow II                                                                                |
| Martin Archer Shee                 | Sir Lewis as the Marquis in The Midnight Hour                                          |
| Mikalojus Konstantinas Čiurlionis  | Creation of the World⁠—V                                                                |
| Mikalojus Konstantinas Čiurlionis  | Creation of the World⁠—III                                                              |
| N. C. Wyeth                        | One More Step, Mr. Hands                                                               |
| Ole Peter Hansen Balling           | General Ulysses S. Grant in the Trenches before Vicksburg                              |
| Richard Wilson                     | St. Peter’s and the Vatican from the Janiculum, Rome                                   |
| Samuel Laurence                    | Charles Babbage, F.R.S.                                                                |
| Stuart Walker                      | Composition No. 61                                                                     |
| Thomas Eakins                      | The Thinker: Portrait of Louis N. Kenton                                               |
| Thomas Lawrence                    | John Philip Kemble, as Coriolanus in Coriolanus by William Shakespeare                 |
| William Logsdail                   | St. Martin-in-the-Fields                                                               |
| William Segar                      | The Ermine Portrait of Elizabeth I of England                                          |
+------------------------------------+----------------------------------------------------------------------------------------+
```

so it was worth it to take a closer look in order to fix those titles. It turned out to be an easy enough fix. I pushed the change that did so as a separate commit (that I'll squash later).

**Review by jobcurtis — APPROVED** [review]
Alright, I've had a play around with this tool and it's very nice. Happy for this to be merged.

**Comment by colagrosso** [comment]
Right on, Job. Thanks for the review, including trying out the script. Merging now.

**Pull request merged**
