### PR TITLE
First stab at an accessibility page

### PR DESCRIPTION
**Pull request by robinwhittleton**
The goal here is to keep it concise: mission, ebooks, web and support. We can adapt this over time as necessary, but this feels good enough as a first attempt.

### CODE REVIEW

**Comment by acabal** [comment]
Looks pretty good. The only thing to note is that in the header template, `highlight` refers to which top nav item is currently highlighted. There is no item for `accessibility`, so we should either highlight `about` or nothing.

**Comment by acabal** [comment]
Should this live under `/about`? I.e. `/about/accessibility`?

**Comment by robinwhittleton** [comment]
Yeah, that feels reasonable. I’ll fix that here, and update the ONIX templates too.

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
