### PR TITLE
Improve instructions on dealing with commas and periods within quotes

### PR DESCRIPTION
**Pull request by weijia-cheng**
Provide a helpful interactive-sr command (something I use myself anyways) instead of just telling people the regex. Also a helpful warning.

### CODE REVIEW

**Comment by acabal** [comment]
I think it might be even clearer if we expanded the example a little bit. What's an example of a plural possessive in a sentence, vs. something that needs correcting?

**Comment by weijia-cheng** [comment]
Ok, how about this? I played around with the manual in a docker container and came up with this. It has examples of what is acceptable and what is not, based on the spacing list. (I used <code> because it's hard to distinguish between the fixed and unfixed versions otherwise.)

**Comment by acabal** [comment]
OK, but it should be `your guys` not `you guys`, and I don't think the comma in `Hello` is grammatically correct either. Maybe just pull a sentence from an existing production as an example instead of trying to come up with our own?

**Comment by weijia-cheng** [comment]
Ok, maybe these should be more compelling examples.

**Comment by acabal** [comment]
`This wood now is not mine, but yours, you peasants’.` is also grammatically incorrect.  You're making `peasants` possessive but you're addressing the plural, not possessive, peasants with `you`.

**Comment by weijia-cheng** [comment]
Ok, I was just copying something I saw in Tolstoy but I can see the problem. I tweaked it a bit to `This wood now is not mine, but the peasants’.` which is more standard grammatically.

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
